const INCREASE_COUNTER = 'INCREASE_COUNTER';
const DECREASE_COUNTER = 'DECREASE_COUNTER';
const RESET_COUNTER = 'RESET_COUNTER';
const SET_COUNTER = 'SET_COUNTER';
const RANDOM_COUNTER = 'RANDOM_COUNTER';
const COUNTER_LOADING = 'COUNTER_LOADING';

export {
  INCREASE_COUNTER,
  DECREASE_COUNTER,
  RESET_COUNTER,
  SET_COUNTER,
  RANDOM_COUNTER,
  COUNTER_LOADING,
};
